name: Snake Animation Generator

on:
  schedule:
    - cron: "0 0 * * *"  # Her gün saat 00:00'da çalıştırır
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v3

      - name: Yılan Animasyonunu Oluştur
        uses: Platane/snk@v3
        with:
          github_user_name: mfy98
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Animasyonu Yayınla
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
