  name: Yılan Animasyonu Oluşturucu

  on:
    schedule:
      # Her gün UTC 03:10'da çalıştırılır
      - cron: '10 3 * * *'
    workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        # Depoyu klonlama
        - name: Depoyu Klonla
          uses: actions/checkout@v3

        # Yılan animasyonunu oluşturma
        - name: Yılan Animasyonunu Oluştur
          uses: Platane/snk@v3
          with:
            github_user_name: mfy98
            outputs: |
              dist/github-snake.svg

        # Oluşturulan animasyonu output dalına gönderme
        - name: Animasyonu Yayınla
          uses: crazy-max/ghaction-github-pages@v3.1.0
          with:
            target_branch: output
            build_dir: dist
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
