name: Generate Snake Animation

on:
  # Her gün saat 00:00'da çalıştırmak için
  schedule:
    - cron: "0 0 * * *"
  # Manuel olarak çalıştırmak için
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Animation and Deploy
    runs-on: ubuntu-latest
    steps:
      # Depoyu klonlama
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Yılan animasyonunu oluşturma
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: mfy98
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Oluşturulan animasyonu output dalına gönderme
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
